### ISSUE TITLE
Add a ModelChoice preference

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/django-dynamic-preferences#10]
This one will be a bit tricky because we need to delete the preference when the selected model is deleted. It can probably be done with a pre_save or a post_save signal, but we need to think about it.

**Comment by n3storm** [comment]
I would suggest another approach: if model doesn't exist disable preference at the moment of instanting. What leads us to see if we can have an active/inactive param in database. I may be complicating everything....

**Comment by EliotBerriot** [comment]
Adding a column to all preferences just for this use case seems a bit hackish to me, as it also means obsolete preferences will remain in DB until cleaned up manually.

I find the signal approach is more synchronous and closer to real database integrity. Exactly, this is what I have in mind (pseudo code, untested):

```python
def create_deletion_handler(preference):
    """Will generate a dynamic handler to purge related preference on instance deletion"""
    def delete_related_preferences(sender, instance, *args, **kwargs):
        queryset = preference.registry.preferences_model.objects\
                                      .filter(name=preference.name, 
                                              section=preference.section)
        related_preferences = queryset.filter(value=preference.serializer.serialize(instance.pk))
        related_preferences.delete()
        

class ModelChoicePreference(IntegerPreference):
    def __init__(self, *args, **kwargs):
        super(ModelChoicePreference, self).__init__(*args, **kwargs)
        self._setup_signals()
        
    def _setup_signals(self):
        handler = create_deletion_handler(self)
        pre_save.connect(handler, sender=self.queryset.model)
        
        
@global_preferences_registry.register
class FeaturedEntry(ModelChoicePreference):
    section = 'general'
    name = 'featured_entry'
    queryset = BlogEntry.objects.all()
```

**Comment by n3storm** [comment]
Looks OK for me
