### ISSUE TITLE
PerInstanceViewSet not filtering preferences based on related instance

### ISSUE THREAD

**Issue by rvignesh89** [EliotBerriot/django-dynamic-preferences#103]
## Steps to reproduce

1. Register max_articles `IntegerPreference` preference to user using `UserPreferenceRegistry` with a default of 10.
2. Create 2 users( lets say user1 & user2)
3. Register `UserPreferencesViewSet` to point to `/api/user/preferences/`
4. Request preferences of user1. This returns 1 preference record.
5. Request preferences of user2. 

## Expected Behavior

There is 1 record of max_articles with a value of 10 which belongs to user2.

## Actual Behaviour

There are 2 records of max_articles with values 10 which belong to user1 and user.

Verified that the other record belongs to user1 by changing user1 max_articles preference to be different that user2.

I'll add a PR with a failing test case illustrate the case soon. My expectation for `PerInstancePreferenceViewSet` is to return only records belonging to that instance which is why I think this is a bug in the package. From what I understand this is caused because of the following,

```
class PreferenceViewSet(
        mixins.UpdateModelMixin,
        mixins.ListModelMixin,
        mixins.RetrieveModelMixin,
        viewsets.GenericViewSet):
    
  ...

    def get_queryset(self):
        ... 
        self.init_preferences()
        return super(PreferenceViewSet, self).get_queryset() # There is no filtering of this queryset based on the instance.
```

I was able return only the requested user preference by overriding the get_queryset in the UserPreferenceViewSet manually like below,

```
class CustomUserPreferencesViewSet(UserPreferencesViewSet):
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(instance=self.request.user)
```

**Comment by EliotBerriot** [comment]
This is strange because I remember adding some code to implement that, as you can see [here](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/api/viewsets.py#L159) and [here](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/users/viewsets.py#L14)

**Comment by rvignesh89** [comment]
From what I understand of the registry and manager(which is not very clear to me yet) I think `get_related_instance` and `get_manager` seems to only load the cache if it does not already have the preferences.

Anyways I just pushed a PR with a failing case. You can take a look at it and see if it makes sense :)

**Comment by EliotBerriot** [comment]
Thank you, I'll look into that. I think the User case is quite different from others (usually, you want user to interact with their own preferences, and it can be different for other per-instance preference).

So we'll have to think about a way to easily enforce that policy on the User viewset, while keeping things open for other use cases.

**Comment by EliotBerriot** [comment]
I'm really sorry I did not post any update on this. I'm in the middle of starting a new job at a new company in another town, so I'm a bit swamped these days. 

It should be better after next week ;)

**Comment by EliotBerriot** [comment]
Another user reported me the same bug on telegram.

**Comment by rvignesh89** [comment]
I understand your situation. I'm able to workaround this by overriding `get_queryset` in my inherited `PerInstancePreferenceViewSet` so I'm okay with the fix being a little late. I can attempt to fix it if you'd like :)

**Comment by EliotBerriot** [comment]
Since you already have submitted a working test case to reproduce this bug, I have to admin i'd be more than happy to let you finish this job, otherwise I plan to spend a few hours working on the project this week-end :)

**Comment by rvignesh89** [comment]
Alright I'll continue with the PR for the fix. I'll try to get it done by this weekend as well.
