### ISSUE TITLE
form.save() doesn't exist

### ISSUE THREAD

**Issue by bjesus** [EliotBerriot/django-dynamic-preferences#120]
Hello!
It seems like django-dynamic-preferences is everything I ever needed, but I'm not sure how to use it and it seems like to documentation can be sometimes outdated.

I have a custom model that I attached django-dynamic-preferences. It's called `Client`. I manage to create an automatic form for it using `dynamic_preferences.forms.preference_form_builder`, and it displays just fine. I can't get it to save though - after creating my form using `client_preference_form_builder(client, request.POST)` , `form.save()` returns `AttributeError: type object 'CustomClientPreferenceForm' has no attribute 'save'`.

Am I doing something incorrectly? I couldn't really find any examples for that in the documentation.

Thank you very much for the great package.
I'd be happy to help with the docs after I'll figure out what I did wrong :) 

Django==1.11.6
django-dynamic-preferences==1.4
Running over ArchLinux with PostgreSQL for what it matters.

**registries.py**
```
from dynamic_preferences.registries import PerInstancePreferenceRegistry

class ClientPreferenceRegistry(PerInstancePreferenceRegistry):
    pass

client_preferences_registry = ClientPreferenceRegistry()
```
**forms.py**
```
from dynamic_preferences.forms import preference_form_builder, PreferenceForm
from .registries import client_preferences_registry

class ClientPreferenceForm(PreferenceForm):
    registry = client_preferences_registry

def client_preference_form_builder(instance, preferences=[], **kwargs):
    return preference_form_builder(
        ClientPreferenceForm, preferences, model={'instance': instance}, **kwargs)
```
**models.py**
```
from django.db import modelsfrom dynamic_preferences.models import PerInstancePreferenceModel

class Client(models.Model):
    created = models.DateTimeField("creation date", auto_now_add=True)
    modified = models.DateTimeField("modification date", auto_now=True)

class ClientPreferenceModel(PerInstancePreferenceModel):
    instance = models.ForeignKey(Client)

    class Meta:
        app_label = 'users'
```

**Comment by EliotBerriot** [comment]
I'd be interested to know how you manipulate the form in your view. I think the confusion here comes from the fact that the form builder returns a `Form` subclass, and not a form instance:

```
# pseudocode
MyFormClass = form_builder()
form = MyFormClass(data)
form.update_preferences()
```

Can you please share your view code, so we can see how you deal with the form instanciation? Also, the form returned by the form builder is not a regular `ModelForm`, as internally, it deals with multiple preferences objects. The proper way to persist the form data once the data is cleaned is to call `update_preferences()` on the form object, instead of `save()`.

I agree with you anyway: the docs would probably benefit from a more complete overview of the API on this part :)

**Comment by bjesus** [comment]
Thanks so much! this pseudo code gave a big enough hint and it's working now.

For the record, my view code works as follow now:
```
def client_settings(request, client_id):
    client = Client.objects.get(id=client_id)
    ClientForm = client_preference_form_builder(client)
    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.update_preferences()
            ClientForm = client_preference_form_builder(client)  # I'm creating the form here again so it would reflect the changes I just saved
    return render(request, 'settings.pug', {
        'form': ClientForm,
})
```

**Comment by EliotBerriot** [comment]
Great, I'm glad you sorted this out!

Don't be afraid of asking your questions here in the future :)
