### ISSUE TITLE
Regression: Section no longer importable from types in 1.4

### ISSUE THREAD

**Issue by shaib** [EliotBerriot/django-dynamic-preferences#121]
Hello,

In 1.3.x you could (and we did...) write a line:
```python
from dynamic_preferences.types import Section, StringPreference
```
In 1.4 or 1.4.1 this no longer works, one needs to write
```python
from dynamic_preferences.preferences import Section
from dynamic_preferences.types import StringPreference
```
I've seen no reference to this on the change log.

**Comment by EliotBerriot** [comment]
Thanks for the bug report, this is indeed serious. It was removed acidentally in this commit: https://github.com/EliotBerriot/django-dynamic-preferences/commit/8125f50f1d130ebd01a82a9228ae8d3f73fce844#diff-a47816f7362053a57fe923b8bcd8b6e6L14

I'll submit a release with a fix this evening (EST).

**Comment by EliotBerriot** [comment]
Release 1.4.2 available on PyPi with a fix for this, sorry for the trouble!

**Comment by rvignesh89** [comment]
Ah, I removed the imports since they were not being referenced. @EliotBerriot apologies for my error! I didn't know this was a behaviour of the app. Do you think it makes sense to add a test to ensure this behaviour is documented?

**Comment by shaib** [comment]
Wow. This was an impressively fast response. Thanks a bunch -- for the package as a whole, and for this in particular!
