### ISSUE TITLE
Concurrent preferences fetch causes duplicate records to be saved 

### ISSUE THREAD

**Issue by rvignesh89** [EliotBerriot/django-dynamic-preferences#126]
I just now ran into what I think is a serious issue when retrieving a preference setting using restframework. This was for a PerInstancePreference model that I've created in my app. The exact scenario is below,

1. User sends request to register
2. The following steps run in an atomic context
2.1 User model is saved
2.2 Save 2 user preferences
2.3 Some other models for user are saved
2.2 Successful registration response is returned
3. User requests 2 different settings that were created in step 2.2

At step 3 I got an error saying there are more than one objects returned for the given section and name. This did not happen always which leads me to conclude that this is due to race conditions. However I'm not able to pinpoint exactly the issue thats happening here.

Some questions that I have
1. Even though I've already saved the 2 preferences in step 2.2, retrieving them in 3 causes them to be re-created. Could this be because the register action is being wrapped inside an atomic transaction?
2. I can overcome this problem by not retrieving preferences individually in step 3. However I'm concerned about what happens when a new preference is added. And different users request for the preferences to be loaded. Would this lead to multiple settings being created as well?

Will running the `checkpreferences ` command help me to solve problem 2?

**Comment by rvignesh89** [comment]
I realise I haven't written any tests to confirm this behaviour. Will do that in the next couple of days.

**Comment by EliotBerriot** [comment]
I'm really sorry, I wrote you an answer today, but I must have cloose my browser window without actually sneding it.

What I would like to see is the complete stack trace of your issue, described in 3. 

It should not be possible to save duplicate preferences, as we have constraints enforced at database level : https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/models.py#L94

If you disable temporarily transactions, do you still face the issue? Dynamic-preferences was wrote at a time when I was not really aware of transactions, and I can think of many places where transactions could break things, e.g all cache-related functions that are not wrapped in a "on_commit" hook.

**Comment by rvignesh89** [comment]
Since I overwrote the Meta class in my PreferenceModel the unique constraint has not been applied. I've fixed this by inheriting the parent Meta. This should prevent duplicates from being saved. 

However I suspect the transaction still causes some errors. I won't have time in the next couple of weeks to look into this as I'm on vacation. Will do it once I'm back next year!

**Comment by rvignesh89** [comment]
Since the time that I reported it I haven't faced this issue. Even after adding the unique constraint I did not see any errors due due duplicate preferences. However I think with multiple instances of the app running might have a chance of producing failures due to race conditions. I have added some workarounds in my application to prevent them.

I'm closing this issue as I don't see others facing the same problem as well.

**Comment by MicahLyle** [comment]
For anyone that finds this later.

If you don't use sections (and hence get a `NULL` `section` in the database), the unique constraint may or may not be enforced depending on how the database handles `NULL`s in the first column of a unique constraint. In my current understanding, many databases will not enforce the second value's (`name` in this case after `section`) uniqueness if the first value is null.

From Cockroach DB's docs, for example:

```
You can insert NULL values into columns with the UNIQUE constraint because NULL is the absence of a value, so it is never equal to other NULL values and not considered a duplicate value. This means that it's possible to insert rows that appear to be duplicates if one of the values is NULL.

If you need to strictly enforce uniqueness, use the [NOT NULL constraint](https://www.cockroachlabs.com/docs/v22.2/not-null) in addition to the UNIQUE constraint. You can also achieve the same behavior through the table's [Primary Key](https://www.cockroachlabs.com/docs/v22.2/primary-key).
```

^ Source: https://www.cockroachlabs.com/docs/stable/unique.html

The fix on the codebase side would be to make the empty/unspecified section be the empty string instead of `NULL` so that uniqueness is still enforced in the DB.
