### ISSUE TITLE
Enable instance preferences generation via admin

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/django-dynamic-preferences#13]
Right now, there is now easy way to generate the default preferences for a model instance (such as `User`). We should provide a shortcut in admin to allow populating of default preference, which is required for further editing.

**Comment by jwaschkau** [comment]
You can add this function yourself:

```python
def init_user_preferences(modeladmin, request, queryset):
    for user in queryset:
        for preference in user.preferences:
            user.preferences[preference] = user.preferences[preference]  # noqa


init_user_preferences.short_description = "Initialize user preferences"


# Define a new User admin
class PreferenceUserAdmin(admin.ModelAdmin):
    actions = (init_user_preferences,)

# Re-register UserAdmin
admin.site.unregister(User)
admin.site.register(User, PreferenceUserAdmin)
``

**Comment by EliotBerriot** [comment]
Thank you for the snippet, I think calling `user.preferences.all()` is enough to trigger the population of default preferences :)

I'll close this anyway, since it's fairly easy to do as you suggested.
