### ISSUE TITLE
Is still alive this project?

### ISSUE THREAD

**Issue by Allan-Nava** [EliotBerriot/django-dynamic-preferences#136]
I have a configuration for my custom app, and I want to modify this dict:
```
WEEKLY_AIMS_LIMITS = {
    WeeklyAims.CREATE_MATCHES                   : 1,
    WeeklyAims.ASSIGN_MATCH_ACTIONS             : 1,
    WeeklyAims.ASSIGN_MARKER_MATCHES            : 1,
    WeeklyAims.CREATE_IMAGES                    : 2,
    WeeklyAims.CREATE_VIDEOS                    : 1,
    WeeklyAims.CREATE_LIKES                     : 5,
    WeeklyAims.CREATE_COMMENTS                  : 5,
    WeeklyAims.CREATE_VIDEO_FROM_APP            : 1,
}
```

I want to update this dict dynamically

**Comment by EliotBerriot** [comment]
Hello! The project is indeed alive, but pretty stable in its current form.

I'm not sure I understand your need correctly, so you'll have to elaborate a bit. What is your configuration, what is your app, etc. Otherwise I won't be able to help you :)

**Comment by Allan-Nava** [comment]
Hi @EliotBerriot , I need to modify this parameters is like a struct with admin interface.

is possible?

**Comment by EliotBerriot** [comment]
Yes, it's possible, you could either split those settings in dedicated preferences, as shown in [the documentation](https://django-dynamic-preferences.readthedocs.io/en/latest/) or store directly a json encoded string in a single preference.

On a side note, please do not open so many issues on many projects just to ask if it is alive or with vague questions. It's an additional burden on maintainers.

I you would like someone to help you or answer your question, please take some time yourself to explain your problem clearly, give some context, tell us what you've tried before, what work, what did not, etc.

It will make it easier to help you ;)

I'm closing this now.
