### ISSUE TITLE
UserPreferenceModel table exists in database even if relevant app is disabled

### ISSUE THREAD

**Issue by czlee** [EliotBerriot/django-dynamic-preferences#140]
Relates to #33, but I'm opening a new issue because that one was closed a while ago.

If I'm not mistaken, the migration [0004_move_user_model.py](https://github.com/EliotBerriot/django-dynamic-preferences/blob/11fa16a2034b70064a57abe01afd7336fcb3a78f/dynamic_preferences/migrations/0004_move_user_model.py) added in 11fa16a2034b70064a57abe01afd7336fcb3a78f doesn't actually remove the model from the database, so if you migrate on a blank database, you'll find that the `dynamic_preferences_users_userpreferencemodel` table still appears, even if `'dynamic_preferences.users.apps.UserPreferencesConfig'` isn't in `INSTALLED_APPS`. I think that operation _moves_ an existing table (the old `dynamic_preferences_userpreferencemodel` table_ to the `users` app by renaming it within the database, and in a _separate_ operation, causing the `dynamic_preferences` app to _believe_ the model no longer exists (because it's no longer its concern). The effect is (probably?) as follows:

- If you _are_ using per-user preferences, the database ends up correct, because it was created in the initial migration, dissociated with the `dynamic_preferences` app, then associated with the `users` app.
- If you're not, there's a stray table in there—I assume the exact table we wanted to avoid—because it was created in the initial migration, then dissociated with the `dynamic_preferences` app.

I'm not totally sure what the solution is, since we'd have to reconcile two things:

1. If someone who is using per-user preferences migrates from pre-separate-app to post-separate-app, then the data should be retained in the database and simply migrated over, not destroyed.

2. If someone who is not using per-user preferences starts an app, the initial migration should not add the `dynamic_preferences_users_userpreferencemodel` table.

In terms of practical effects, the stray table causes `manage.py flush` to fail, because now there's a table present in the database that Django doesn't know about, which depends on `auth_user` (which Django does know about), so it can't run the `TRUNCATE` operation:

```
migrate=> TRUNCATE "availability_roundavailability", "checkins_event", "participants_team", "auth_user_user_permissions", "django_content_type", "auth_user_groups", "adjfeedback_adjudicatorfeedbackquestion", "checkins_identifier", "adjallocation_adjudicatorinstitutionconflict", "results_ballotsubmission", "draw_debateteam", "venues_venue", "adjfeedback_adjudicatorfeedback", "jet_pinnedapplication", "motions_debateteammotionpreference", "options_tournamentpreferencemodel", "privateurls_privateurlsentmailrecord", "django_admin_log", "participants_institution", "draw_teamsideallocation", "adjfeedback_adjudicatorfeedbackbooleananswer", "auth_permission", "breakqual_breakcategory", "adjfeedback_adjudicatorfeedbackstringanswer", "actionlog_actionlogentry", "auth_group", "adjfeedback_adjudicatorfeedbackintegeranswer", "adjallocation_adjudicatoradjudicatorconflict", "auth_user", "dynamic_preferences_globalpreferencemodel", "results_speakerscorebyadj", "adjfeedback_adjudicatortestscorehistory", "adjallocation_adjudicatorconflict", "venues_venueconstraint", "checkins_personidentifier", "divisions_division", "motions_motion_divisions", "results_teamscore", "venues_venuecategory_venues", "participants_person", "participants_speaker_categories", "adjfeedback_adjudicatorfeedbackfloatanswer", "adjallocation_debateadjudicator", "participants_adjudicator", "tournaments_tournament", "auth_group_permissions", "motions_motion", "django_summernote_attachment", "checkins_debateidentifier", "jet_bookmark", "draw_debate", "tournaments_round", "venues_venuecategory", "participants_region", "participants_speakercategory", "participants_team_break_categories", "participants_speaker", "django_session", "results_speakerscore", "breakqual_breakingteam", "checkins_venueidentifier";
ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "dynamic_preferences_users_userpreferencemodel" references "auth_user".
```

Any thoughts?

cc @philipbelesky

**Comment by EliotBerriot** [comment]
Yep, this is not good :/

I'm reluctant to modify the first migration because of unforeseen consequences. Ideally, I'd like some way to completely remove user preferences from the base app, but I don't find an easy way to do that. I'm open to ideas.

Here is a brief history if needed:

1. Initial releases of DDP where bundling user and global preferences in the same app (thus, in the same migrations)
2. Later, we moved user preferences to a separate app, but we had to deal with the legacy, so we dit not edit the initial migration and tried to remain backward compatible
3. Now

Sorry, I know I'm not really helpful on this :/ Maybe someone else will an idea to clear up this mess while not breaking existing installations (unless providing a clear upgrade path). I'm completely open to discussion on this!
