### ISSUE TITLE
Add a MultipleModelChoice preference

### ISSUE THREAD

**Issue by eriktelepovsky** [EliotBerriot/django-dynamic-preferences#143]
Hi. I am looking for a solution to store multiple instances into preference. Is it possible to create something like MultipleModelChoice preference like in issue #10 please?

**Comment by EliotBerriot** [comment]
Yes it is possible! Actually, I have [a basic implementation in another project](https://code.eliotberriot.com/funkwhale/funkwhale/blob/develop/api/funkwhale_api/common/preferences.py#L17-49) that works for lists of strings (maybe it is enough for you?). 

I still need to backport here though, but maybe you can try this snippet in your own project and tell me how it works for you?

**Comment by eriktelepovsky** [comment]
Thanks @EliotBerriot ;) I'll give it a shot and let you know.

**Comment by eriktelepovsky** [comment]
I think it will be even better to inherit from ``ChoicePreference`` instead of ``BasePreferenceType``:

```Python
class StringListPreference(ChoicePreference):
    serializer = StringListSerializer
    field_class = forms.MultipleChoiceField

    def get_api_additional_data(self):
        d = super(StringListPreference, self).get_api_additional_data()
        d["choices"] = self.get("choices")
        return d

    def validate(self, value):
        for v in value:
            super(StringListPreference, self).validate(v)
```

**Comment by eriktelepovsky** [comment]
I implemented a new preference type for storing multiple model instances. Check it out.
