### ISSUE TITLE
Support for rest_framework 3.8

### ISSUE THREAD

**Issue by rvignesh89** [EliotBerriot/django-dynamic-preferences#156]
According to `rest_framework` 3.8 [announcement](http://www.django-rest-framework.org/topics/3.8-announcement/#breaking-changes) `list_route` is going to be deprecated. @EliotBerriot do you have any plans to look into this? 

I just updated one of my apps to 3.9 and started to see annoying warnings while running my tests which is why I'm asking 😬

**Comment by EliotBerriot** [comment]
Thank you for opening the issue, I'll consider that before next release :)

**Comment by exequiel09** [comment]
Is this still an issue? I saw that #180 which contains djangorestframework 3.10.x compatibility commit was merged.

**Comment by EliotBerriot** [comment]
Yep, we can close, thanks!
