### ISSUE TITLE
Running `makemigrations` creates a new migration file for `dynamic_preferences`

### ISSUE THREAD

**Issue by exequiel09** [EliotBerriot/django-dynamic-preferences#160]
This is running using `dynamic_preferences` v1.7.

See the attached screen shot:
<img width="1275" alt="screen shot 2018-11-20 at 10 09 56 am" src="https://user-images.githubusercontent.com/1289472/48746932-88e46680-ecac-11e8-82a8-309efd7a4849.png">
<img width="1280" alt="screen shot 2018-11-20 at 10 10 10 am" src="https://user-images.githubusercontent.com/1289472/48746943-90a40b00-ecac-11e8-90ac-d522b038391b.png">

**Comment by EliotBerriot** [comment]
Indeed, that's an issue, I forgot to run them recently. Do you want to open a PR with the migrations? Otherwise I can do it myself :)

**Comment by exequiel09** [comment]
Sorry for the late reply. Created a PR with the missing migrations file.
