### ISSUE TITLE
Customize basic admin view

### ISSUE THREAD

**Issue by zbynekdrlik** [EliotBerriot/django-dynamic-preferences#162]
Is it possible to remove some columns from basic admin views of ddp? I like to remove section name and default value.

Zbynek

**Comment by EliotBerriot** [comment]
Hi @zbynekdrlik !

Yes, it's possible. Basically, you have to unregister our admin module, and replace it with your own:

```python
from django.contrib import admin
from dynamic_preferences.admin import GlobalPreferenceAdmin
from dynamic_preferences.models import GlobalPreferenceModel
admin.site.unregister(GlobalPreferenceModel)

class CustomGlobalPreferenceAdmin(GlobalPreferenceAdmin):
    list_display = (
        'verbose_name',
        'name',
        # 'section_name',
        'help_text',
        'raw_value',
        # 'default_value'
    )

admin.site.register(GlobalPreferenceModel, CustomGlobalPreferenceAdmin)
```

**Comment by zbynekdrlik** [comment]
Thanks. It works. Finally for my app it will be better to have configuration in view mode, not in list mode. I hope to set preference fields by fieldsets. So I can format and group fields on one settings page. Same as if I have one line model configuration (present implementation)

![image](https://user-images.githubusercontent.com/26905282/49214922-f0df2f00-f3c7-11e8-8571-6d1ecad6c313.png)

How to do this?

**Comment by EliotBerriot** [comment]
I'm sorry @zbynekdrlik, but I'm not familiar enough with the django's admin to help you there.
