### ISSUE TITLE
choices display string

### ISSUE THREAD

**Issue by zbynekdrlik** [EliotBerriot/django-dynamic-preferences#164]
In standart django model choices it is possible use 
get_fieldname_display() 
which return choosed display string of choices index. Is it possible with ChoicePreference?

**Comment by EliotBerriot** [comment]
No, it's not possible right now, but you can access preference's choices calling [this method](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/types.py#L241). It's more verbose, but you can write a small helper to find the proper display string for any given value :)

**Comment by zbynekdrlik** [comment]
Ok Thanks
