### ISSUE TITLE
Preference of BooleanPreference type must use required = False if one wants to allow False values for the preference

### ISSUE THREAD

**Issue by serbant** [EliotBerriot/django-dynamic-preferences#167]
This is not necessarily a bug but it can be confusing since False is as valid a value as True.
To follow the django style, somebody needs to add a NullBooleanPreference type. The other option would be to allow for False and reject None.

**Comment by EliotBerriot** [comment]
I use boolean preferences in projects, and both True and False values work correctly for me (in the admin and the REST API). Where do you encounter this behaviour?

**Comment by serbant** [comment]
When trying to set a BooleanPreference to False in the admin, I get an
error message

**Comment by EliotBerriot** [comment]
Does it change anything if you add `field_kwargs = {"required": False}` on your pereference configuration?

```
@global_preferences_registry.register
class MyBooleanPreference(types.BooleanPreference):
    name = "test"
    default = False
    field_kwargs = {"required": False}
```

**Comment by serbant** [comment]
haven't tried that one. it works with required = False and that's good
enough for me

**Comment by EliotBerriot** [comment]
Perfect, I'm closing then :)
