### ISSUE TITLE
how do i set : change_globalpreferencemodel

### ISSUE THREAD

**Issue by gonzaloamadio** [EliotBerriot/django-dynamic-preferences#169]
I want to add the DRF endpoint, and only want admin user to change them.

Where do I set the permission change_globalpreferencemodel ?

Thank you

**Comment by EliotBerriot** [comment]
Hi @gonzaloamadio, our DRF endpoint is a traditionnal DRF viewset. Anything that is valid with DRF should work here as well. You can declare your permissions as shown here: https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy
