### ISSUE TITLE
Error adding endpoint:  'Specifying a namespace in include() without providing an app_name '

### ISSUE THREAD

**Issue by gonzaloamadio** [EliotBerriot/django-dynamic-preferences#170]
I want to add the DRF endpoints, but when adding them to urls.py, I have the following error
   
url(r'^preferences/', include(router.urls, namespace='preferences'))
 File "/home/gonzalo/.virtualenvs/tektank-ws/lib/python3.6/site-packages/django/urls/conf.py", line 39, in include
   'Specifying a namespace in include() without providing an app_name '
jango.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name
attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.

In my installed apps, I have an app "global_parameters" , added like this:

    'tektank.apps.global_parameters.apps.GlobalParametersConfig'

And my apps.py inside the app , it is:

```
from django.apps import AppConfig                                                                             
class GlobalParametersConfig(AppConfig):               
    name = 'global_parameters'                         

```

**Comment by EliotBerriot** [comment]
Hi @gonzaloamadio, our documentation is probably a bit outdated, but you can likely fix the issue by passing `url(r'^preferences/', include((router.urls, 'preferences'), namespace='preferences')` or ditching the namespace completely :)
