### ISSUE TITLE
Cannot access user settings on admin

### ISSUE THREAD

**Issue by johanneshk** [EliotBerriot/django-dynamic-preferences#172]
Hi,
I don't seem to see the user settings on the admin page. Just to clarifiy: I should be able to access those via the user page on the admin? I can access global_preferences just fine.

I started just with the base version and now added 'dynamic_preferences.users.apps.UserPreferencesConfig' to INSTALLED_APPS. I also registered the preference in my_app/dynamic_preferences_registry.py: 

```
@user_preferences_registry.register
class DailyMailReportsEnabled(BooleanPreference):
    name = 'DailyMailReportsEnabled'
    section = user_settings_section
    default = False
```
I can access this preference via the shell:

```
from django.contrib.auth import get_user_model

user = get_user_model().objects.get(username='admin')
user.preferences

> {'user_settings__DailyMailReportsEnabled': False}
```

I just don't see it on user admin... Did I miss something (I most likely did)?

Thanks,
 Johannes

django-dynamic-preferences==1.7

**Comment by EliotBerriot** [comment]
So the admin page is there, but it's empty?

Hm I haven't used this feature in a long time, I'd probably need to check by hand.

**Comment by johanneshk** [comment]
I can access global preferences on on the admin just fine (/admin/dynamic_preferences/globalpreferencemodel/) but I am under the impression that I should be able to change user preferences on the admin as well? Or did I misunderstand that? I can change them via shell just fine.

Thanks.

**Comment by EliotBerriot** [comment]
Yes, you should be. Are you not seeing the user preferences admin page at all?

**Comment by johanneshk** [comment]
Call me stupid / blind... I looked for user preferences below the 'Dynamic Preferences' section of the admin, but it's below 'Preferences - Users'. Sorry about that...

**Comment by EliotBerriot** [comment]
You're not stupid, don't be sorry, it's ok to ask questions @johanneshk :)
