### ISSUE TITLE
Migration Dependency Issue

### ISSUE THREAD

**Issue by cw-intellineers** [EliotBerriot/django-dynamic-preferences#176]
When I try to migrate a fresh database, I always get the following error:

`django.db.utils.ProgrammingError: relation "dynamic_preferences_globalpreferencemodel" does not exist`

This kind of makes sense, because it probably tries to create the preferences in the database before the actual migrations are made. I use a custom Auth Model and the Auth App has its own Preferences. Therefore I am kind of stuck at the moment. A workaround is, to always comment all references out in the root urls file and then do the initial migrations and then continue.

Does anybody have an idea how to get around this?

**Comment by EliotBerriot** [comment]
A bug is possible, but this shouldn't happen, unless you have some code that is triggered at *import* time that query preferences. Is this the case in your project?

**Comment by cw-intellineers** [comment]
I have some custom querysets, but thats about it. How do I know if there are triggered at import time?

**Comment by cw-intellineers** [comment]
So I was digging a bit deeper and found the line of code that causes the error:

1. The urls.py gets evaluated
2. The views.py gets evaluated
3. The view calls <Model>.<custom_model_manager>.all()
4. The custom_model_manager calls global_preference_registry.manager(). This tries to connect to the database and the error happens, because the database is not yet migrated. I could surround this with try/catch, but this seems somehow wrong to me...

Any ideas what I can do about this?

**Comment by cw-intellineers** [comment]
So for now, I just have a try/catch block around it, then it works. however this seems wrong to me, but maybe i just don't get the full picture.

**Comment by EliotBerriot** [comment]
@cw-intellineers if importing `views.py` triggers the issue, it means you have some code that calls the database trigerred at import-time (vs at run-time, e.g when someone requests your site).

This is usually a bad idea because:

1. importing modules shouldn't have sive effects (querying the DB, doing HTTP request, etc.)
2. if you query at import time instead of at run time, the preference value won't change

Consider this code:

```python

from dynamic_preferences.registries import global_preferences_registry
global_preferences = global_preferences_registry.manager()
site_name = global_preferences['general__title']

def my_view(request):
    return 'Site name is {}'.format(site_name)
```

Since `site_name` is defined at the top level, it's evaluated when you import the module. This is bad, because if you change the `general__title` preference via the admin, then `my_view` will continue to reference the old value.

The correct way to do is:

```python

from dynamic_preferences.registries import global_preferences_registry

def my_view(request):
    global_preferences = global_preferences_registry.manager()
    site_name = global_preferences['general__title']
    return 'Site name is {}'.format(site_name)
```

I may give you more help if you share the content of your `views.py` file

**Comment by cw-intellineers** [comment]
Below you find an extract of the source code. I think I do it the same as you.

views.py:
```
class EmployeeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Person.employees.all()
```

models.py
```
class PersonEmployeeManager(models.Manager):
    def get_queryset(self):
        global_preferences = global_preferences_registry.manager()
        return super().get_queryset().filter(employer__id=global_preferences['crm__main_company'])

class Person(models.Model):
    employees =  PersonEmployeeManager()
    objects = models.Manager()
```

**Comment by EliotBerriot** [comment]
@cw-intellineers 

You have this in your views, which is evaluated at import time: `queryset = Person.employees.all()`

This triggers immediatly your `get_queryset` method, leading to the issue I described above.

A possible solution is to replace your view by this:

```
class EmployeeViewSet(viewsets.ReadOnlyModelViewSet):
    def get_queryset(self):
        return Person.employees.all()


```

**Comment by cw-intellineers** [comment]
Thanks a lot. I will try this out.

**Comment by cw-intellineers** [comment]
Worked. Thanks.
