### ISSUE TITLE
Moving from 1.6 to 1.7.1, a migration file is detected

### ISSUE THREAD

**Issue by briandestura** [EliotBerriot/django-dynamic-preferences#185]
If we install version 1.7.1 from 1.6, django's makemigrations is detecting a migration file:

```
python manage.py makemigrations
Migrations for 'dynamic_preferences':
  /Users/.virtualenvs/lib/python3.6/site-packages/dynamic_preferences/migrations/0006_auto_20190924_0442.py
```

Is this intended? Shouldn't this be shipped with the package?

EDIT: Looks like it came from https://github.com/EliotBerriot/django-dynamic-preferences/blob/12eab4f17b960290525b215d954d1b5fb91199df/dynamic_preferences/models.py#L21

We are using Django 1.11

**Comment by EliotBerriot** [comment]
What is the content of the migration file @briandestura?

**Comment by briandestura** [comment]
I got this:

`class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_preferences', '0005_auto_20181120_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferencemodel',
            name='section',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name'),
        ),
    ]
`

From the history of the `models.py`, it was generated because of `verbose_name`

**Comment by exequiel09** [comment]
I think we should just create a new migration file for this. I could create a PR if you want.

**Comment by EliotBerriot** [comment]
Sure @exequiel09, I'd gladly accept a PR for this :)

**Comment by briandestura** [comment]
I was gonna do it but did not know if it was intended or not 😆 
Thanks @exequiel09 @EliotBerriot
