### ISSUE TITLE
Convert sections to Python objects

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/django-dynamic-preferences#19]
When I designed sections, I thought of the section name as a slug, short identifier, not a verbose name that will be displayed to end users. But we need to store additional data on sections, such as a verbose, translatable name, and maybe some common behaviour that will apply on all preferences.

So, the current section system, based on a single identifier has to evolve to plain Python objects. The API could probably looks like :

    @sections.register
    class CMSPosts(Section):
        name = 'cms_post'
        verbose_name = _('CMS Posts')

The challenge here will be to keep backward-compatibility.

**Comment by n3storm** [comment]
I think in a couple of weeks I can have this done. Tell me if is an appropiate timespan. Cheers

**Comment by EliotBerriot** [comment]
It would be really great ! There is absolutely no urge for this, and a couple of weeks are fine :)

**Comment by EliotBerriot** [comment]
I'm gonna work on it, I have some spare time right now :)
