### ISSUE TITLE
Preferences not refreshing

### ISSUE THREAD

**Issue by lorenzomorandini** [EliotBerriot/django-dynamic-preferences#191]
Hi, we've been using this package in our projects for quite some time now, so thank you.
I've found a problem tho, not sure if it's a bug or a misconfiguration by us.

After editing a preference thru the admin, the running processes doesn't seem to see the change and still have the old value. A restart of the WSGI server fixes it. Is it supposed to happen?

**Comment by lorenzomorandini** [comment]
I think it may be related to putting the

    global_preferences = global_preferences_registry.manager()

inside a function/class or outside

**Comment by EliotBerriot** [comment]
Hi @lorenzomorandini, can you share the code were accessing preferences return stale values? `global_preferences_registry.manager` must be instanciated and used at runtime (vs import time)

**Comment by lorenzomorandini** [comment]
Ok that's the error then, I was using it outside a fuction. Thank you.

**Comment by EliotBerriot** [comment]
you're welcome, thank you for the update :)
