### ISSUE TITLE
filepreferences show file after click

### ISSUE THREAD

**Issue by zbynekdrlik** [EliotBerriot/django-dynamic-preferences#197]
When file is successfully  uploaded by fileprefferenece there is not possible to show that file after click on blue link. What to setup to work?

```
@global_preferences_registry.register
class IdFile(FilePreference):
    name = 'id_file'
    verbose_name = 'Identifikačne údaje xml'
```

**Comment by EliotBerriot** [comment]
@zbynekdrlik are you referring to a file uploaded through the admin, or through a custom  form?

**Comment by zbynekdrlik** [comment]
I am using admin, and it is soled by setup correct MEDIA_ROOT and MEDIA_URL in settings.py
