### ISSUE TITLE
Emit signal on change of preference

### ISSUE THREAD

**Issue by Natureshadow** [EliotBerriot/django-dynamic-preferences#207]
I am currently trying to migrate the AlekSIS project from constance to django-dynamic-preferences. One missing part is that we need to invalidate a cache if one global preference is changed, so I'd like to have a signal emitted after update of a preference (much like the [setting_changed signal](https://docs.djangoproject.com/en/3.0/ref/signals/#setting-changed) in Django itself).

I looked into jsut using the `post_save` signal on `BasePreferenceModel`, but it does not allow to detect which preference was updated.

Another approach with a much smaller changeset would be to pass `section` and `name` as `update_fields` to the `save` call in the manager when saving the model, which will make its way through to the recipient of the `post_save` signal, but this does not look like "one obvious way" to me in terms of the Zen of Python.

I am willing to contribute this feature if the maintainer(s) do not generally object to it.

**Comment by EliotBerriot** [comment]
Looks like an interesting feature. What about we emit a dedicated signal in https://github.com/EliotBerriot/django-dynamic-preferences/blob/bfb602dbd0486ceb2fe19e5ed8acc5bdb4c77131/dynamic_preferences/managers.py#L151 ?

Something like:

```python
import django.dispatch

preference_updated = django.dispatch.Signal(providing_args=["section", "name", old_value", "new_value"])
```

And in `def update_db_pref`, call this signal with the proper arguments? In my opinion, it would be cleaner from a design perspective.

**Comment by Natureshadow** [comment]
Yep, exactly that!
