### ISSUE TITLE
[QUESTION] How do I update the preferences of arbitrary model in Django REST Framework?

### ISSUE THREAD

**Issue by awebartisan** [EliotBerriot/django-dynamic-preferences#215]
I have a model named Post. I associated the preferences with it and I am able to retrieve them as Post object children on API endpoint.

But how do I update them? Will there be a separate endpoint needed like `post/1/preferences` ? 

Any example would be of great help. Thanks :)

**Comment by EliotBerriot** [comment]
Hi @awebartisan, you can have a look at our [REST API documentation](https://django-dynamic-preferences.readthedocs.io/en/latest/rest_api.html) to implement this.
