### ISSUE TITLE
Change CharField max_length from 255 to 191 for support of utf8mb4 when using db_index=True

### ISSUE THREAD

**Issue by falknes** [EliotBerriot/django-dynamic-preferences#23]
Hi

Would it be possible to change max_length of CharFields where db_index=True in the models from 255 to a value usable with encoding ``utf8mb4``?

From:
```python
class BasePreferenceModel(models.Model):
    section = models.CharField(
        max_length=255, db_index=True, blank=True, null=True, default=None)
    name = models.CharField(max_length=255, db_index=True)
```

To for example:
```python
class BasePreferenceModel(models.Model):
    section = models.CharField(
        max_length=191, db_index=True, blank=True, null=True, default=None)
    name = models.CharField(max_length=191, db_index=True)
```

Having section and name thats 255 characters long feels like overkill, and changing it to a smaler value will also make it usable in mysql without enabling "innodb_large_prefix" when using true utf8 support. In my case, I dont have access to change the innodb_large_prefix setting.

``utf8mb4`` max key length at the moment is 191 characters

When i try to run `python manage.py syncdb` it throws an exception.
```
pymysql.err.InternalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

Best regards
/falknes

**Comment by phoebebright** [comment]
Just hit the same error and agree that section and name unlikely to need to be that long.

**Comment by EliotBerriot** [comment]
Sorry, I was really late on this. Thank you for reporting the issue, it was fixed in tag 0.6.4, which has been published to PyPi.

**Comment by phoebebright** [comment]
That was quick!  The only problem is that when I run migrate it's still trying to run the initial migration with the long fields!

**Comment by EliotBerriot** [comment]
Damn, you're right, my fix wasn't so clever after all ;) I'm gonna make a new release.

**Comment by phoebebright** [comment]
:-)

**Comment by EliotBerriot** [comment]
This time it should be ok, can you confirm this ?

**Comment by phoebebright** [comment]
migration 2 needs reducing as well

**Comment by EliotBerriot** [comment]
I pushed a corrected version of migration 0002 (didn't made a release this time, I expect something to go wrong for the third time). You can install the develop version via `pip install https://github.com/EliotBerriot/django-dynamic-preferences/archive/develop.zip`.

**Comment by phoebebright** [comment]
Yes that works now.

**Comment by EliotBerriot** [comment]
Glad to hear that, the 0.6.6 release that includes all this changes has just been pushed to PyPi.
