### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'name'

### ISSUE THREAD

**Issue by mkoskela** [EliotBerriot/django-dynamic-preferences#27]
I'm hitting the following AttributeError exception when trying to access dynamic preferences (global, user, or custom) in Django admin:

````
File "/path/to/my/virtualenv/lib/python2.7/site-packages/dynamic_preferences/models.py", line 72, in __repr__
return '{0} - {1}/{2}'.format(self.__class__.__name__, self.section.name, self.name)

AttributeError: 'unicode' object has no attribute 'name'
````

After debugging the error, I noticed that self.section is an Unicode object and hence cannot have a 'name' attribute. If self.section.name is replaced with self.section, everything works.

Environment: Python 2.7.9, Django 1.8.5, django-dynamic-preferences 0.6.2

**Comment by EliotBerriot** [comment]
This issue was solved in PR #26 , but I did not make a release. I'll do it now, since it is a serious issue.

**Comment by EliotBerriot** [comment]
The 0.6.3 release which includes this fix has been published to PyPi :)

**Comment by mkoskela** [comment]
Wow, that was fast! Thanks!

**Comment by EliotBerriot** [comment]
You're welcome, in fact, @pomerama is responsible for this, as I didn't notice the issue.
