### ISSUE TITLE
Enable deactivation of user-level settings (User preferences).

### ISSUE THREAD

**Issue by macolo** [EliotBerriot/django-dynamic-preferences#33]
User-level prefs might confuse admin users, shouldn't there be a way to remove that entry completely from the admin interface?

**Comment by philipbelesky** [comment]
```python
from django.contrib import admin
from dynamic_preferences.models import UserPreferenceModel
admin.site.unregister(UserPreferenceModel)
```
Is what I've been using, would that work for your purpose?

**Comment by EliotBerriot** [comment]
You're right, this is a problem, since the feature and the model are enabled even if the project does not need them. @philipbelesky answer's should work to disable this, but implementing user preferences in a dedicated app inside `dynamic_preferences` would be the correct way to solve the issue on the long term.

**Comment by macolo** [comment]
@philipbelesky thanks, that works perfectly! @EliotBerriot agree, however feel free to close this issue nonetheless :)

**Comment by EliotBerriot** [comment]
I'll keep the issue open to remember we need a better documentation on how to disable the User preference model, and a refactoring of the whole user-related stuff has to beconsidered sooner or later.

**Comment by JetUni** [comment]
This is how I disable the user preference model in the database admin, and it's documented:

https://django-dynamic-preferences.readthedocs.io/en/stable/installation.html#settings

**Comment by EliotBerriot** [comment]
Yes, I've added the setting to disable the admin link, however, the underlying model is still present in database. The only way to fix this properly is to move  user preferences to a dedicated app, but this is heavy work.
