### ISSUE TITLE
Name and Category should be immutable in Django Admin (editable=false)

### ISSUE THREAD

**Issue by macolo** [EliotBerriot/django-dynamic-preferences#35]
As the name and category of a setting is hardcoded, Django Admin should not allow to update these fields.

When I try to change a setting name or category in Django Admin I get, rightfully so, a NotFoundInRegistry error.

I feel that there is room for UX improvements.

**Comment by EliotBerriot** [comment]
Yes, you're definitely right! Thank you for reporting this.
