### ISSUE TITLE
Syntax and other corrections in documentation

### ISSUE THREAD

**Issue by bittner** [EliotBerriot/django-dynamic-preferences#39]
There are some syntax flaws, logical and spelling mistakes I noticed reading the documentation, e.g.

* [x] Links use Markdown syntax instead of reStructuredText syntax in [README.rst](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/README.rst) (introduction chapter) and [AUTHORS.rst](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/AUTHORS.rst) (i.e. the Credits section).
* [x] "PyPi" should be spelled with a captial eye ("PyPI") in [installation.rst](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/docs/installation.rst).
* [x] No need for `python manage.py syncdb` in [installation.rst](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/docs/installation.rst) if you support Django 1.7+ only.
* [x] "nex time" should be "next time" (tee missing) in [quickstart.rst](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/docs/quickstart.rst#under-the-hood), "Under The Hood" section.
* [x] The [Pull Request Guidelines](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/CONTRIBUTING.rst#pull-request-guidelines) in the Contributing chapter mention Python 2.6, 2.7, and 3.3 whereas the README talks about "Python 2.7 and 3.4, with django 1.7 and 1.8".
* [x] The README is included in the documentation twice, as an introduction and as a [final chapter](https://django-dynamic-preferences.readthedocs.org/en/latest/readme.html).

Potential improvements:

* [ ] The chapters [Upgrade](https://django-dynamic-preferences.readthedocs.org/en/latest/upgrade.html) and [Changelog](https://django-dynamic-preferences.readthedocs.org/en/latest/history.html) could be combined somehow for easier understanding and maintenance.

Hope that helps. It's not a PR, but better than no feedback at all. :pensive:

**Comment by EliotBerriot** [comment]
I'm glad you reported this, there is definitely a room for improvement and better consistency in the documentation. I'm also starting to think it's time to move some parts of the Quickstart to dedicated pages : I'd rather have a short Quickstart, with links to dig deeper if needed.

It helps a lot, even without the PR, thanks for the help !
