### ISSUE TITLE
create_default_per_instance_preferences() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by phoebebright** [EliotBerriot/django-dynamic-preferences#48]
I would like to suggest making the arguments optional in the signal create_default_per_instance_preferences.

The error above was caused by neomodel library and is probably something that should be fixed that end, however, given that this app only cares about created, this fix would make it more robust.

def create_default_per_instance_preferences(sender, created=None, instance=None, **kwargs):

What do you think?

**Comment by EliotBerriot** [comment]
Could you please post the full stack trace? I'd like to have a bit more context to understand exactly the issue ;)

**Comment by phoebebright** [comment]
This is the code in neomodel that is hooking up signals:

    def exec_hook(hook_name, self, *args, **kwargs):
    
            if hasattr(self, hook_name):
                getattr(self, hook_name)(*args, **kwargs)
            if signals and hasattr(signals, hook_name):
                sig = getattr(signals, hook_name)
                sig.send(sender=self.__class__, instance=self)   <-----  calls only with sender and instance, no created argument
    
    
     def hooks(fn):
    
        def hooked(self, *args, **kwargs):
            fn_name = fn.func_name if hasattr(fn, 'func_name') else fn.__name__
            exec_hook('pre_' + fn_name, self, *args, **kwargs)
            val = fn(self, *args, **kwargs)
            exec_hook('post_' + fn_name, self, *args, **kwargs)
    
            return val
    
        return hooked

also causes a problem in the next function: invalidate_cache

Does that help?

**Comment by EliotBerriot** [comment]
Im' sorry, but I'd rather not patch my library when clearly if's a fix that should occur on neomodel side : the `created` and `instance` argument are listed in the [official Django's documentation](https://docs.djangoproject.com/en/1.9/ref/signals/#django.db.models.signals.post_save), so it's neomodel's job to support that.

Also, setting instance and created to None by default would likely raise even stranger, more difficult to debug errors

**Comment by phoebebright** [comment]
No problem, I'll pursue it from that end.  Thanks for the documentation and I'll try the disable option to solve my current problem.
