### ISSUE TITLE
Use verbose_name in sections.html template

### ISSUE THREAD

**Issue by JanMalte** [EliotBerriot/django-dynamic-preferences#49]
Make usage of `verbose_name` in `dynamic_preferences/templates/dynamic_preferences/sections.html` to allow translations and user friendly section names.

**Comment by EliotBerriot** [comment]
You're right, that's a logical fix, I'll work on it ASAP :)

**Comment by EliotBerriot** [comment]
The 1.1 release containing this change was pushed to PyPi :)
