### ISSUE TITLE
ImportError: cannot import name global_preferences_registry

### ISSUE THREAD

**Issue by andykaycodes** [EliotBerriot/django-dynamic-preferences#61]
django-dynamic-preferences (0.8.2)

I am trying to run this project: https://github.com/mfomicheva/tradopad
And the following file fails: https://github.com/mfomicheva/tradopad/blob/master/rater/dynamic_preferences_registry.py

> /Users/andy/tradopad/bin/python /Users/andy/Developer/tradopad/manage.py runserver 8000
> Unhandled exception in thread started by <function wrapper at 0x10a8cc848>
> Traceback (most recent call last):
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
>    fn(*args, **kwargs)
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in > inner_run
>    autoreload.raise_last_exception()
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
>    six.reraise(*_exception)
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
>    fn(*args, **kwargs)
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
>    apps.populate(settings.INSTALLED_APPS)
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
>    app_config.ready()
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/dynamic_preferences/apps.py", line 19, in ready
>    global_preferences_registry.autodiscover(settings.INSTALLED_APPS)
>  File "/Users/andy/tradopad/lib/python2.7/site-packages/persisting_theory/registries.py", line 107, in autodiscover
>    module = __import__(package)
>  File "/Users/andy/Developer/tradopad/rater/dynamic_preferences_registry.py", line 4, in <module>
>    from dynamic_preferences import global_preferences_registry
> ImportError: cannot import name global_preferences_registry

The correct way to import global_preferences_registry seems to be `from dynamic_preferences.registries import global_preferences_registry` -- but it doesn't work either (the same error). I've been only able to do `from dynamic_preferences.registries import user_preferences_registry`

**Comment by EliotBerriot** [comment]
Thank you for reporting this. I cannot reproduce this locally. The correct way to import the `global_preferences_registry` is from `dynamic_preferences.registries`, as shown, for example, in [the project documentation](http://django-dynamic-preferences.readthedocs.io/en/latest/quickstart.html). 

I've cloned your project on my local computer and if i replace `from dynamic_preferences import global_preferences_registry` by `from dynamic_preferences.registries import global_preferences_registry`, the project loads successuflly. Can you confirm this modification works on your side ?

**Comment by andykaycodes** [comment]
Indeed, the project was simply using a wrong way to import the registry. I almost figured it out yesterday but probably messed up something else. Thank you very much for taking your time and for referring me to the documentation. The ticket can be closed.

**Comment by EliotBerriot** [comment]
No problem, I'm glad it's fixed for you :)
