### ISSUE TITLE
NotFoundInRegistry: No such preference in GlobalPreferenceRegistry with section=general and name=title

### ISSUE THREAD

**Issue by jqbao** [EliotBerriot/django-dynamic-preferences#62]
I did a clean install using Django 1.10.1. I followed the tutorial. Not sure why I am getting the following error.

NotFoundInRegistry: No such preference in GlobalPreferenceRegistry with section=general and name=title

**Comment by EliotBerriot** [comment]
I'm sorry you encountered an error while setting up the project ! Would you mind share the full stack trace and the code that trigger the error ? This way I can help you debugging this.

Thanks :)

**Comment by jqbao** [comment]
Internal Server Error: /control_panel/view/preferences/
Traceback (most recent call last):
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jqbao/Documents/github/views/page_requests/control_panel_pages.py", line 69, in control_panel_preferences
    assert global_preferences['general__title'] == 'My site'
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/dynamic_preferences/managers.py", line 27, in __getitem__
    return self.get(key)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/dynamic_preferences/managers.py", line 94, in get
    db_pref = self.get_db_pref(section=section, name=name)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/dynamic_preferences/managers.py", line 103, in get_db_pref
    pref_obj = self.pref_obj(section=section, name=name)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/dynamic_preferences/managers.py", line 70, in pref_obj
    return self.registry.get(section=section, name=name)
  File "/Users/jqbao/VirtualEnvironment/lib/python2.7/site-packages/dynamic_preferences/registries.py", line 123, in get
    self.__class__.__name__, section, name))
NotFoundInRegistry: No such preference in GlobalPreferenceRegistry with section=general and name=title

**Comment by jqbao** [comment]
When the app loads, should the preferences defined in dynamic_preferences_registry.py be populated in the database?

**Comment by EliotBerriot** [comment]
Can you share the content of the following files:

- dynamic_preferences_registry.py
- settings.py
- views.py

Feel free to include more data regarding your project layout (your app names, etc.)

**Comment by jqbao** [comment]
dynamic_preferences_registry.py

from dynamic_preferences.types import BooleanPreference, StringPreference, Section
from dynamic_preferences.registries import user_preferences_registry, global_preferences_registry

# we create some section objects to link related preferences together

general = Section('general')
discussion = Section('discussion')

# We start with a global preference
@global_preferences_registry.register
class SiteTitle(StringPreference):
    section = general
    name = 'title'
    default = 'My site'

@global_preferences_registry.register
class MaintenanceMode(BooleanPreference):
    name = 'maintenance_mode'
    default = False

# now we declare a per-user preference
@user_preferences_registry.register
class CommentNotificationsEnabled(BooleanPreference):
    """Do you want to be notified on comment publication ?"""
    section = discussion
    name = 'comment_notifications_enabled'
    default = True

**Comment by jqbao** [comment]
settings.py
`# Application definition
INSTALLED_APPS = (
    'apps.preferences',
    'dynamic_preferences',

)`

**Comment by jqbao** [comment]
views.py

```
def control_panel_preferences(request):
    # We instantiate a manager for our global preferences

    global_preferences = global_preferences_registry.manager()
    assert global_preferences['general__title'] == 'My site'
    print global_preferences['general__title']
    return render(request, 'ui/control_panel/control_panel_preferences.html', {})
```

**Comment by jqbao** [comment]
At which point is it supposed to populate the database with preferences?

**Comment by jqbao** [comment]
I found out I had to place dynamic_preferences_registry.py in the root of my app. If my app is called preferences and I wand to put the dynamic_preferences_registry.py file under preferences->views->dynamic_preferences_registry.py. Do I have to edit the DYNAMIC_PREFERENCES setting?

**Comment by EliotBerriot** [comment]
You can edit the settings `DYNAMIC_PREFERENCES['REGISTRY_MODULE']` (as described [here](http://django-dynamic-preferences.readthedocs.io/en/latest/installation.html#settings)) if you want a custom path for your registry files, but I would recommend keeping this file at the root of your app.
