### ISSUE TITLE
Provide documentation for subclassing PerInstancePreferenceModel 

### ISSUE THREAD

**Issue by mosspaper** [EliotBerriot/django-dynamic-preferences#63]
I'd like to subclass PerInstancePreferenceModel to be able to attach preferences to any custom model. Any documentation on this would be great!

**Comment by EliotBerriot** [comment]
@mosspaper I've added a PR (#65) regarding your issue, would you mind read the proposed documentation and try it in your own project? Feel free to report anything misleading or not working so I can update the documentation accordingly :)

**Comment by EliotBerriot** [comment]
Sorry, the relevant link to the documentation section is here: https://github.com/EliotBerriot/django-dynamic-preferences/blob/feature/permodel-preferences/docs/bind_preferences_to_models.rst

**Comment by mosspaper** [comment]
@EliotBerriot I just followed the updated documentation and tried it in my own project. Everything works great! Only thing is there is a typo in the import statement in one of the sections (Create a registry to collect your model preferences). Thanks again for adding this!

```
# yourapp/apps.py

from dynamic_preferences.registries import preference_modelsglobal_preferences_registry

```

**Comment by EliotBerriot** [comment]
I'm really glad it help, feel free to ask for more documentations when needed, we cannot have too much ;)
