### ISSUE TITLE
"section" should be passed in context of PreferenceFormView

### ISSUE THREAD

**Issue by leetucker** [EliotBerriot/django-dynamic-preferences#71]
I am modifying the default version of the preference form templates in order to integrate the design with my overall site.  However, the PreferenceFormView currently provides very little context information, and it would be very useful in particular to have the current section (for section-specific page titles).

Something like this in views.PreferenceFormView.get_context_data would be a start:

`context['section'] = self.kwargs.get('section', None)`

However, since it would also be particularly helpful to have the verbose name, I won't put this through as a pull request.

**Comment by EliotBerriot** [comment]
Thank you for reporting this. It seems like a reasonable demand, I think the best thing would be to pass the section object itself (and not only the identifier from the url) in the context, meaning you can get the verbose_name from it in your template, or any other custom attribute (if you sublassed the base `Section` class).

Do you you think such a patch would solve your issue ?

**Comment by EliotBerriot** [comment]
I think it is also linked to #49

**Comment by leetucker** [comment]
Yes, this would be perfect.  I also agree that it is related to #49, as it would be particularly helpful to have access to all of the verbose_names in creating a custom navigation menu.

**Comment by EliotBerriot** [comment]
The 1.1 release containing this change was pushed to PyPi :)
