### ISSUE TITLE
'NoneType' object has no attribute 'objects' in edit preferences view

### ISSUE THREAD

**Issue by JanMalte** [EliotBerriot/django-dynamic-preferences#73]
I get an error `'NoneType' object has no attribute 'objects'` on the preferences view, as the `preference_model` is not set on the user preferences registry.

**Comment by JanMalte** [comment]
Seems like `'dynamic_preferences.users',` is not enough, as there is no `default_app_config = 'dynamic_preferences.users.apps.UserPreferencesConfig'` in `dynamic_preferences/users/__init__.py`

The complete app config path `'dynamic_preferences.users.apps.UserPreferencesConfig',` must be added to `INSTALLED_APPS`

**Comment by EliotBerriot** [comment]
This is advertised in the [installation](https://django-dynamic-preferences.readthedocs.io/en/latest/installation.html#setup) and [upgrade to 1.0](https://django-dynamic-preferences.readthedocs.io/en/latest/upgrade.html#id1) guide, but maybe there are still some old documentation parts that requires an update?

Feel free to reopen if you think the documentation could be improved regarding this :)

**Comment by JanMalte** [comment]
Thanks, the documentation is fine. I just tried the "short/old" way of adding apps to the `INSTALLED_APPS`, as I'm using `django-permission` which is not yet capable of the new `AppConfig` feature as of https://github.com/lambdalisue/django-permission/issues/60
