### ISSUE TITLE
Registry object has no attribute 'create_default_preferences'

### ISSUE THREAD

**Issue by jeffreybrowning** [EliotBerriot/django-dynamic-preferences#78]
When using home-baked preferences and the `UserPrefereceModel` included in your lib, I cannot trigger default preference generation in neither an interactive shell nor in the django admin. 

`'OrgPreferenceRegistry' object has no attribute 'create_default_preferences'`
and
`'UserPreferenceRegistry' object has no attribute 'create_default_preferences'`

Where exactly is `create_default_preferences` defined? When can I expect default preferences to be created? 

This is the function being triggered on `post_save`:

```
def create_default_per_instance_preferences(sender, created, instance, **kwargs):
    """Create default preferences for PerInstancePreferenceModel"""

    if created:
        try:
            registry = preference_models.get_by_instance(instance)
            registry.create_default_preferences(instance)
        except AttributeError:
            pass
```

I am using Django 1.11 and python 3.6. I can create stubs of the code to help if required.

**Comment by EliotBerriot** [comment]
Indeed, that snippet simply does not work, as the `create_default_preferences` is defined nowhere.

I think this is something that wa not finished as it was not needed: preferences are created with their default values when you access them using the manager.

For exemple, if you have a newly created  `user` instance and some `notification_receive_by_mail` preferences with a default value to `True`, the following should pass:

```python
assert user.preferences['notification_receive_by_mail'] is True
```

Internally, when accessing preferences via the `preferences` attribute on the instance, it will create them in database if they don't exist. If you want to get them (and therefore, create them) all at once, you can call `user.preferences.all()`.

One of the reason not to create them by default each time you save a new user is that it will trigger additional database queries, depending of the number of preferences you registered in your app. If you have 10 preferences, saving a new user would result in 11 SQL requests: one for actually saving the user, and one to persist each default preference.

I think it's better to keep this lazy bahaviour as a default, but if you have some use case where you want to create these preferences by default on the related instance creation, feel free to expose it, we could easily implement a setting or a switch to allow this.

Anyhow, I'll keep this issue open as a reminder to deal with this code (by either removing it or actually implementing it). If anybody want to pick this issue, it should be fairly easy :)
