### ISSUE TITLE
Add a  Date and a DateTime preference

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/django-dynamic-preferences#8]

**Comment by rvignesh89** [comment]
@EliotBerriot are you working on this ATM? If not I could help out this week as I need these types in my app. And now that #97 is fixed I should be able to use that as a reference to do this. 

Have you also considered adding Duration preference?

**Comment by EliotBerriot** [comment]
@rvignesh89 I'm not working on this, so your help is welcome. I'm not against a duration preference either. Let me know if you need any help or review while implementing this :)

**Comment by rvignesh89** [comment]
Awesome, I'll push a PR for this in the next few days.
