### ISSUE TITLE
Unable to set optional preferences

### ISSUE THREAD

**Issue by swalladge** [EliotBerriot/django-dynamic-preferences#84]
It would be nice to be able to allow 'optional' preferences. For example is currently possible to set an empty string as the default for the `StringPreference` type, but it is not possible to set it to an empty string from admin, - it comes back with `This field is required.`.

Something like:

```
@global_preferences_registry.register
class Thing(StringPreference):

    section = site
    name = 'string_thing'
    help_text = 'an optional string that can be set to empty string if you want'
    default = ''
    required = False
    # or maybe:
    # blank = True
```

**Comment by EliotBerriot** [comment]
You can solve this by overriding the `get_field_kwargs` method on your preference:

```python
@global_preferences_registry.register
class Thing(StringPreference):
    section = site
    name = 'string_thing'
    help_text = 'an optional string that can be set to empty string if you want'
    default = ''
    
    def get_field_kwargs(self):
        kwargs = super().get_field_kwargs()
        kwargs['required'] = False
        return kwargs
```

Those kwargs are passed to the underlying form field (which is generated dynamically), and you can pass any option that is accepted by the field class you use.

Overriding a method for this simple task is bit verbose though, and a better API would probably be:


```python
@global_preferences_registry.register
class Thing(StringPreference):
    section = site
    name = 'string_thing'
    help_text = 'an optional string that can be set to empty string if you want'
    default = ''
    field_kwargs = {
        'required': False
    }
```

What do you think?

**Comment by swalladge** [comment]
Great! As long as it's possible, that's fine (Nice to be documented though). I agree the second dictionary based API is cleaner.

**Comment by EliotBerriot** [comment]
I've added some documentation and code relevant for this in 1.3.1, you can look at the docs: https://django-dynamic-preferences.readthedocs.io/en/latest/quickstart.html#form-fields
