### ISSUE TITLE
Empty string in StringPreference serializes to 'None'

### ISSUE THREAD

**Issue by swalladge** [EliotBerriot/django-dynamic-preferences#85]
As in the title. I think it's because for some reason when the string preference is set to an empty string, it comes back from the db as `None`, which is then serialized as a string with `return str(value)`.

This basically makes it impossible to set an empty string in a StringPreference.

**Comment by EliotBerriot** [comment]
Thanks for the report, you indeed found a bug.

You can solve this in your own project by doing this:

```python
from dynamic_preferences.serializers import StringSerializer

class FixedStringSerializer(StringSerializer):
    @classmethod
    def to_python(cls, value, **kwargs):
        # this is the important bit that is currently missing
        if not value:
            return ''
        try:
            return str(value)
        except: pass
        try:
            return value.encode('utf-8')
        except: pass
        raise cls.exception("Cannot deserialize value {0} tostring".format(value))

class YourPreference(StringPreference):
    serializer = FixedStringSerializer
```

I'll try to publish a release including a patch for this during the weekend.

Sorry for the trouble!

**Comment by swalladge** [comment]
No trouble, I was about to work on a PR if you haven't already started on it?

**Comment by EliotBerriot** [comment]
Sure a PR is welcome (include a unittest if you can, otherwise  I'll do it myself later)!

**Comment by swalladge** [comment]
Ok, right on it - I'll add a test as well.
