### ISSUE TITLE
Add a ChoicePreference

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/django-dynamic-preferences#9]

**Comment by philipbelesky** [comment]
Isn't this already added?

**Comment by EliotBerriot** [comment]
I think I started to implement this some time ago, but stopped in the middle : I can find a `ChoicePreference` class, but no related unittest. Before closing this, some tests should be written, and probably some documentation too.

**Comment by swalladge** [comment]
I just tried using `ChoicePreference`, but it crashes with `too many values to unpack (expected 2)` with django 1.11.3.

**Comment by EliotBerriot** [comment]
@swalladge can you please tell me which version of dynamic_preferences you are using?

**Comment by swalladge** [comment]
@EliotBerriot version 1.3

**Comment by EliotBerriot** [comment]
Okay thanks, I'll look in to this issue in the following days (probably tomorrow night).

**Comment by EliotBerriot** [comment]
@swalladge I've started working on this and I do not get any error in tests. Can you please give me more context about how you get the issue? I'm interested in:

- The full stack trace of the error
- Your corresponding `Preference` class so I can have a look at how you configured it
- What were you trying to achieve: updating a preference, accessing it's value, from code, from the admin?

**Comment by swalladge** [comment]
@EliotBerriot annoyingly, I can't reproduce it again... it's working fine! Not sure what changed. Sorry for the time waster.

**Comment by EliotBerriot** [comment]
No problem, I'm glad it's solved anyway :) I'll push a commit that includes unittest, to ensure it does not break again.
